/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetAuthJellyfinQuickconnectCheck2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAuthJellyfinQuickconnectCheck2XXResponse{}

// GetAuthJellyfinQuickconnectCheck2XXResponse struct for GetAuthJellyfinQuickconnectCheck2XXResponse
type GetAuthJellyfinQuickconnectCheck2XXResponse struct {
	Authenticated *bool `json:"authenticated,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAuthJellyfinQuickconnectCheck2XXResponse GetAuthJellyfinQuickconnectCheck2XXResponse

// NewGetAuthJellyfinQuickconnectCheck2XXResponse instantiates a new GetAuthJellyfinQuickconnectCheck2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAuthJellyfinQuickconnectCheck2XXResponse() *GetAuthJellyfinQuickconnectCheck2XXResponse {
	this := GetAuthJellyfinQuickconnectCheck2XXResponse{}
	return &this
}

// NewGetAuthJellyfinQuickconnectCheck2XXResponseWithDefaults instantiates a new GetAuthJellyfinQuickconnectCheck2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAuthJellyfinQuickconnectCheck2XXResponseWithDefaults() *GetAuthJellyfinQuickconnectCheck2XXResponse {
	this := GetAuthJellyfinQuickconnectCheck2XXResponse{}
	return &this
}

// GetAuthenticated returns the Authenticated field value if set, zero value otherwise.
func (o *GetAuthJellyfinQuickconnectCheck2XXResponse) GetAuthenticated() bool {
	if o == nil || IsNil(o.Authenticated) {
		var ret bool
		return ret
	}
	return *o.Authenticated
}

// GetAuthenticatedOk returns a tuple with the Authenticated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAuthJellyfinQuickconnectCheck2XXResponse) GetAuthenticatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Authenticated) {
		return nil, false
	}
	return o.Authenticated, true
}

// HasAuthenticated returns a boolean if a field has been set.
func (o *GetAuthJellyfinQuickconnectCheck2XXResponse) HasAuthenticated() bool {
	if o != nil && !IsNil(o.Authenticated) {
		return true
	}

	return false
}

// SetAuthenticated gets a reference to the given bool and assigns it to the Authenticated field.
func (o *GetAuthJellyfinQuickconnectCheck2XXResponse) SetAuthenticated(v bool) {
	o.Authenticated = &v
}

func (o GetAuthJellyfinQuickconnectCheck2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAuthJellyfinQuickconnectCheck2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authenticated) {
		toSerialize["authenticated"] = o.Authenticated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAuthJellyfinQuickconnectCheck2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varGetAuthJellyfinQuickconnectCheck2XXResponse := _GetAuthJellyfinQuickconnectCheck2XXResponse{}

	err = json.Unmarshal(data, &varGetAuthJellyfinQuickconnectCheck2XXResponse)

	if err != nil {
		return err
	}

	*o = GetAuthJellyfinQuickconnectCheck2XXResponse(varGetAuthJellyfinQuickconnectCheck2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authenticated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAuthJellyfinQuickconnectCheck2XXResponse struct {
	value *GetAuthJellyfinQuickconnectCheck2XXResponse
	isSet bool
}

func (v NullableGetAuthJellyfinQuickconnectCheck2XXResponse) Get() *GetAuthJellyfinQuickconnectCheck2XXResponse {
	return v.value
}

func (v *NullableGetAuthJellyfinQuickconnectCheck2XXResponse) Set(val *GetAuthJellyfinQuickconnectCheck2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAuthJellyfinQuickconnectCheck2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAuthJellyfinQuickconnectCheck2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAuthJellyfinQuickconnectCheck2XXResponse(val *GetAuthJellyfinQuickconnectCheck2XXResponse) *NullableGetAuthJellyfinQuickconnectCheck2XXResponse {
	return &NullableGetAuthJellyfinQuickconnectCheck2XXResponse{value: val, isSet: true}
}

func (v NullableGetAuthJellyfinQuickconnectCheck2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAuthJellyfinQuickconnectCheck2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


