/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the ListJellyfinUsers2XXResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListJellyfinUsers2XXResponseInner{}

// ListJellyfinUsers2XXResponseInner struct for ListJellyfinUsers2XXResponseInner
type ListJellyfinUsers2XXResponseInner struct {
	Username *string `json:"username,omitempty"`
	Id *string `json:"id,omitempty"`
	Thumb *string `json:"thumb,omitempty"`
	Email *string `json:"email,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListJellyfinUsers2XXResponseInner ListJellyfinUsers2XXResponseInner

// NewListJellyfinUsers2XXResponseInner instantiates a new ListJellyfinUsers2XXResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListJellyfinUsers2XXResponseInner() *ListJellyfinUsers2XXResponseInner {
	this := ListJellyfinUsers2XXResponseInner{}
	return &this
}

// NewListJellyfinUsers2XXResponseInnerWithDefaults instantiates a new ListJellyfinUsers2XXResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListJellyfinUsers2XXResponseInnerWithDefaults() *ListJellyfinUsers2XXResponseInner {
	this := ListJellyfinUsers2XXResponseInner{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ListJellyfinUsers2XXResponseInner) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListJellyfinUsers2XXResponseInner) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ListJellyfinUsers2XXResponseInner) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ListJellyfinUsers2XXResponseInner) SetUsername(v string) {
	o.Username = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListJellyfinUsers2XXResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListJellyfinUsers2XXResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListJellyfinUsers2XXResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ListJellyfinUsers2XXResponseInner) SetId(v string) {
	o.Id = &v
}

// GetThumb returns the Thumb field value if set, zero value otherwise.
func (o *ListJellyfinUsers2XXResponseInner) GetThumb() string {
	if o == nil || IsNil(o.Thumb) {
		var ret string
		return ret
	}
	return *o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListJellyfinUsers2XXResponseInner) GetThumbOk() (*string, bool) {
	if o == nil || IsNil(o.Thumb) {
		return nil, false
	}
	return o.Thumb, true
}

// HasThumb returns a boolean if a field has been set.
func (o *ListJellyfinUsers2XXResponseInner) HasThumb() bool {
	if o != nil && !IsNil(o.Thumb) {
		return true
	}

	return false
}

// SetThumb gets a reference to the given string and assigns it to the Thumb field.
func (o *ListJellyfinUsers2XXResponseInner) SetThumb(v string) {
	o.Thumb = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ListJellyfinUsers2XXResponseInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListJellyfinUsers2XXResponseInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ListJellyfinUsers2XXResponseInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ListJellyfinUsers2XXResponseInner) SetEmail(v string) {
	o.Email = &v
}

func (o ListJellyfinUsers2XXResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListJellyfinUsers2XXResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Thumb) {
		toSerialize["thumb"] = o.Thumb
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListJellyfinUsers2XXResponseInner) UnmarshalJSON(data []byte) (err error) {
	varListJellyfinUsers2XXResponseInner := _ListJellyfinUsers2XXResponseInner{}

	err = json.Unmarshal(data, &varListJellyfinUsers2XXResponseInner)

	if err != nil {
		return err
	}

	*o = ListJellyfinUsers2XXResponseInner(varListJellyfinUsers2XXResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "id")
		delete(additionalProperties, "thumb")
		delete(additionalProperties, "email")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListJellyfinUsers2XXResponseInner struct {
	value *ListJellyfinUsers2XXResponseInner
	isSet bool
}

func (v NullableListJellyfinUsers2XXResponseInner) Get() *ListJellyfinUsers2XXResponseInner {
	return v.value
}

func (v *NullableListJellyfinUsers2XXResponseInner) Set(val *ListJellyfinUsers2XXResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListJellyfinUsers2XXResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListJellyfinUsers2XXResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListJellyfinUsers2XXResponseInner(val *ListJellyfinUsers2XXResponseInner) *NullableListJellyfinUsers2XXResponseInner {
	return &NullableListJellyfinUsers2XXResponseInner{value: val, isSet: true}
}

func (v NullableListJellyfinUsers2XXResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListJellyfinUsers2XXResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


