/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the CreateUserSettingsLinkedAccountsJellyfinRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserSettingsLinkedAccountsJellyfinRequest{}

// CreateUserSettingsLinkedAccountsJellyfinRequest struct for CreateUserSettingsLinkedAccountsJellyfinRequest
type CreateUserSettingsLinkedAccountsJellyfinRequest struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateUserSettingsLinkedAccountsJellyfinRequest CreateUserSettingsLinkedAccountsJellyfinRequest

// NewCreateUserSettingsLinkedAccountsJellyfinRequest instantiates a new CreateUserSettingsLinkedAccountsJellyfinRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserSettingsLinkedAccountsJellyfinRequest() *CreateUserSettingsLinkedAccountsJellyfinRequest {
	this := CreateUserSettingsLinkedAccountsJellyfinRequest{}
	return &this
}

// NewCreateUserSettingsLinkedAccountsJellyfinRequestWithDefaults instantiates a new CreateUserSettingsLinkedAccountsJellyfinRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserSettingsLinkedAccountsJellyfinRequestWithDefaults() *CreateUserSettingsLinkedAccountsJellyfinRequest {
	this := CreateUserSettingsLinkedAccountsJellyfinRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) SetPassword(v string) {
	o.Password = &v
}

func (o CreateUserSettingsLinkedAccountsJellyfinRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserSettingsLinkedAccountsJellyfinRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateUserSettingsLinkedAccountsJellyfinRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateUserSettingsLinkedAccountsJellyfinRequest := _CreateUserSettingsLinkedAccountsJellyfinRequest{}

	err = json.Unmarshal(data, &varCreateUserSettingsLinkedAccountsJellyfinRequest)

	if err != nil {
		return err
	}

	*o = CreateUserSettingsLinkedAccountsJellyfinRequest(varCreateUserSettingsLinkedAccountsJellyfinRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUserSettingsLinkedAccountsJellyfinRequest struct {
	value *CreateUserSettingsLinkedAccountsJellyfinRequest
	isSet bool
}

func (v NullableCreateUserSettingsLinkedAccountsJellyfinRequest) Get() *CreateUserSettingsLinkedAccountsJellyfinRequest {
	return v.value
}

func (v *NullableCreateUserSettingsLinkedAccountsJellyfinRequest) Set(val *CreateUserSettingsLinkedAccountsJellyfinRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserSettingsLinkedAccountsJellyfinRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserSettingsLinkedAccountsJellyfinRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserSettingsLinkedAccountsJellyfinRequest(val *CreateUserSettingsLinkedAccountsJellyfinRequest) *NullableCreateUserSettingsLinkedAccountsJellyfinRequest {
	return &NullableCreateUserSettingsLinkedAccountsJellyfinRequest{value: val, isSet: true}
}

func (v NullableCreateUserSettingsLinkedAccountsJellyfinRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserSettingsLinkedAccountsJellyfinRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


