/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetBlocklist2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBlocklist2XXResponse{}

// GetBlocklist2XXResponse struct for GetBlocklist2XXResponse
type GetBlocklist2XXResponse struct {
	PageInfo *PageInfo `json:"pageInfo,omitempty"`
	Results []GetBlocklist2XXResponseResultsInner `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetBlocklist2XXResponse GetBlocklist2XXResponse

// NewGetBlocklist2XXResponse instantiates a new GetBlocklist2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBlocklist2XXResponse() *GetBlocklist2XXResponse {
	this := GetBlocklist2XXResponse{}
	return &this
}

// NewGetBlocklist2XXResponseWithDefaults instantiates a new GetBlocklist2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBlocklist2XXResponseWithDefaults() *GetBlocklist2XXResponse {
	this := GetBlocklist2XXResponse{}
	return &this
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *GetBlocklist2XXResponse) GetPageInfo() PageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret PageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBlocklist2XXResponse) GetPageInfoOk() (*PageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *GetBlocklist2XXResponse) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given PageInfo and assigns it to the PageInfo field.
func (o *GetBlocklist2XXResponse) SetPageInfo(v PageInfo) {
	o.PageInfo = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetBlocklist2XXResponse) GetResults() []GetBlocklist2XXResponseResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []GetBlocklist2XXResponseResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBlocklist2XXResponse) GetResultsOk() ([]GetBlocklist2XXResponseResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetBlocklist2XXResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []GetBlocklist2XXResponseResultsInner and assigns it to the Results field.
func (o *GetBlocklist2XXResponse) SetResults(v []GetBlocklist2XXResponseResultsInner) {
	o.Results = v
}

func (o GetBlocklist2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBlocklist2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetBlocklist2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varGetBlocklist2XXResponse := _GetBlocklist2XXResponse{}

	err = json.Unmarshal(data, &varGetBlocklist2XXResponse)

	if err != nil {
		return err
	}

	*o = GetBlocklist2XXResponse(varGetBlocklist2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pageInfo")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetBlocklist2XXResponse struct {
	value *GetBlocklist2XXResponse
	isSet bool
}

func (v NullableGetBlocklist2XXResponse) Get() *GetBlocklist2XXResponse {
	return v.value
}

func (v *NullableGetBlocklist2XXResponse) Set(val *GetBlocklist2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBlocklist2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBlocklist2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBlocklist2XXResponse(val *GetBlocklist2XXResponse) *NullableGetBlocklist2XXResponse {
	return &NullableGetBlocklist2XXResponse{value: val, isSet: true}
}

func (v NullableGetBlocklist2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBlocklist2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


