/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the CreateUserImportFromJellyfinRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserImportFromJellyfinRequest{}

// CreateUserImportFromJellyfinRequest struct for CreateUserImportFromJellyfinRequest
type CreateUserImportFromJellyfinRequest struct {
	JellyfinUserIds []string `json:"jellyfinUserIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateUserImportFromJellyfinRequest CreateUserImportFromJellyfinRequest

// NewCreateUserImportFromJellyfinRequest instantiates a new CreateUserImportFromJellyfinRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserImportFromJellyfinRequest() *CreateUserImportFromJellyfinRequest {
	this := CreateUserImportFromJellyfinRequest{}
	return &this
}

// NewCreateUserImportFromJellyfinRequestWithDefaults instantiates a new CreateUserImportFromJellyfinRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserImportFromJellyfinRequestWithDefaults() *CreateUserImportFromJellyfinRequest {
	this := CreateUserImportFromJellyfinRequest{}
	return &this
}

// GetJellyfinUserIds returns the JellyfinUserIds field value if set, zero value otherwise.
func (o *CreateUserImportFromJellyfinRequest) GetJellyfinUserIds() []string {
	if o == nil || IsNil(o.JellyfinUserIds) {
		var ret []string
		return ret
	}
	return o.JellyfinUserIds
}

// GetJellyfinUserIdsOk returns a tuple with the JellyfinUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserImportFromJellyfinRequest) GetJellyfinUserIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.JellyfinUserIds) {
		return nil, false
	}
	return o.JellyfinUserIds, true
}

// HasJellyfinUserIds returns a boolean if a field has been set.
func (o *CreateUserImportFromJellyfinRequest) HasJellyfinUserIds() bool {
	if o != nil && !IsNil(o.JellyfinUserIds) {
		return true
	}

	return false
}

// SetJellyfinUserIds gets a reference to the given []string and assigns it to the JellyfinUserIds field.
func (o *CreateUserImportFromJellyfinRequest) SetJellyfinUserIds(v []string) {
	o.JellyfinUserIds = v
}

func (o CreateUserImportFromJellyfinRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserImportFromJellyfinRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JellyfinUserIds) {
		toSerialize["jellyfinUserIds"] = o.JellyfinUserIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateUserImportFromJellyfinRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateUserImportFromJellyfinRequest := _CreateUserImportFromJellyfinRequest{}

	err = json.Unmarshal(data, &varCreateUserImportFromJellyfinRequest)

	if err != nil {
		return err
	}

	*o = CreateUserImportFromJellyfinRequest(varCreateUserImportFromJellyfinRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "jellyfinUserIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUserImportFromJellyfinRequest struct {
	value *CreateUserImportFromJellyfinRequest
	isSet bool
}

func (v NullableCreateUserImportFromJellyfinRequest) Get() *CreateUserImportFromJellyfinRequest {
	return v.value
}

func (v *NullableCreateUserImportFromJellyfinRequest) Set(val *CreateUserImportFromJellyfinRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserImportFromJellyfinRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserImportFromJellyfinRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserImportFromJellyfinRequest(val *CreateUserImportFromJellyfinRequest) *NullableCreateUserImportFromJellyfinRequest {
	return &NullableCreateUserImportFromJellyfinRequest{value: val, isSet: true}
}

func (v NullableCreateUserImportFromJellyfinRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserImportFromJellyfinRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


