/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the TestMetadatas2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestMetadatas2XXResponse{}

// TestMetadatas2XXResponse struct for TestMetadatas2XXResponse
type TestMetadatas2XXResponse struct {
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TestMetadatas2XXResponse TestMetadatas2XXResponse

// NewTestMetadatas2XXResponse instantiates a new TestMetadatas2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestMetadatas2XXResponse() *TestMetadatas2XXResponse {
	this := TestMetadatas2XXResponse{}
	return &this
}

// NewTestMetadatas2XXResponseWithDefaults instantiates a new TestMetadatas2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestMetadatas2XXResponseWithDefaults() *TestMetadatas2XXResponse {
	this := TestMetadatas2XXResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TestMetadatas2XXResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestMetadatas2XXResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TestMetadatas2XXResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TestMetadatas2XXResponse) SetMessage(v string) {
	o.Message = &v
}

func (o TestMetadatas2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestMetadatas2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TestMetadatas2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varTestMetadatas2XXResponse := _TestMetadatas2XXResponse{}

	err = json.Unmarshal(data, &varTestMetadatas2XXResponse)

	if err != nil {
		return err
	}

	*o = TestMetadatas2XXResponse(varTestMetadatas2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestMetadatas2XXResponse struct {
	value *TestMetadatas2XXResponse
	isSet bool
}

func (v NullableTestMetadatas2XXResponse) Get() *TestMetadatas2XXResponse {
	return v.value
}

func (v *NullableTestMetadatas2XXResponse) Set(val *TestMetadatas2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTestMetadatas2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTestMetadatas2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestMetadatas2XXResponse(val *TestMetadatas2XXResponse) *NullableTestMetadatas2XXResponse {
	return &NullableTestMetadatas2XXResponse{value: val, isSet: true}
}

func (v NullableTestMetadatas2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestMetadatas2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


