/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
	"fmt"
)

// checks if the PublicSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicSettings{}

// PublicSettings struct for PublicSettings
type PublicSettings struct {
	Initialized bool `json:"initialized"`
	// Instance Plex OAuth client identifier
	PlexClientIdentifier string `json:"plexClientIdentifier"`
	AdditionalProperties map[string]interface{}
}

type _PublicSettings PublicSettings

// NewPublicSettings instantiates a new PublicSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicSettings(initialized bool, plexClientIdentifier string) *PublicSettings {
	this := PublicSettings{}
	this.Initialized = initialized
	this.PlexClientIdentifier = plexClientIdentifier
	return &this
}

// NewPublicSettingsWithDefaults instantiates a new PublicSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicSettingsWithDefaults() *PublicSettings {
	this := PublicSettings{}
	return &this
}

// GetInitialized returns the Initialized field value
func (o *PublicSettings) GetInitialized() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Initialized
}

// GetInitializedOk returns a tuple with the Initialized field value
// and a boolean to check if the value has been set.
func (o *PublicSettings) GetInitializedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Initialized, true
}

// SetInitialized sets field value
func (o *PublicSettings) SetInitialized(v bool) {
	o.Initialized = v
}

// GetPlexClientIdentifier returns the PlexClientIdentifier field value
func (o *PublicSettings) GetPlexClientIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlexClientIdentifier
}

// GetPlexClientIdentifierOk returns a tuple with the PlexClientIdentifier field value
// and a boolean to check if the value has been set.
func (o *PublicSettings) GetPlexClientIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlexClientIdentifier, true
}

// SetPlexClientIdentifier sets field value
func (o *PublicSettings) SetPlexClientIdentifier(v string) {
	o.PlexClientIdentifier = v
}

func (o PublicSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["initialized"] = o.Initialized
	toSerialize["plexClientIdentifier"] = o.PlexClientIdentifier

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PublicSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"initialized",
		"plexClientIdentifier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicSettings := _PublicSettings{}

	err = json.Unmarshal(data, &varPublicSettings)

	if err != nil {
		return err
	}

	*o = PublicSettings(varPublicSettings)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "initialized")
		delete(additionalProperties, "plexClientIdentifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePublicSettings struct {
	value *PublicSettings
	isSet bool
}

func (v NullablePublicSettings) Get() *PublicSettings {
	return v.value
}

func (v *NullablePublicSettings) Set(val *PublicSettings) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicSettings) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicSettings(val *PublicSettings) *NullablePublicSettings {
	return &NullablePublicSettings{value: val, isSet: true}
}

func (v NullablePublicSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


