/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetCache2XXResponseDnsCacheEntriesValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCache2XXResponseDnsCacheEntriesValue{}

// GetCache2XXResponseDnsCacheEntriesValue struct for GetCache2XXResponseDnsCacheEntriesValue
type GetCache2XXResponseDnsCacheEntriesValue struct {
	Addresses *GetCache2XXResponseDnsCacheEntriesValueAddresses `json:"addresses,omitempty"`
	ActiveAddress *string `json:"activeAddress,omitempty"`
	Family *float32 `json:"family,omitempty"`
	Age *float32 `json:"age,omitempty"`
	Ttl *float32 `json:"ttl,omitempty"`
	NetworkErrors *float32 `json:"networkErrors,omitempty"`
	Hits *float32 `json:"hits,omitempty"`
	Misses *float32 `json:"misses,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCache2XXResponseDnsCacheEntriesValue GetCache2XXResponseDnsCacheEntriesValue

// NewGetCache2XXResponseDnsCacheEntriesValue instantiates a new GetCache2XXResponseDnsCacheEntriesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCache2XXResponseDnsCacheEntriesValue() *GetCache2XXResponseDnsCacheEntriesValue {
	this := GetCache2XXResponseDnsCacheEntriesValue{}
	return &this
}

// NewGetCache2XXResponseDnsCacheEntriesValueWithDefaults instantiates a new GetCache2XXResponseDnsCacheEntriesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCache2XXResponseDnsCacheEntriesValueWithDefaults() *GetCache2XXResponseDnsCacheEntriesValue {
	this := GetCache2XXResponseDnsCacheEntriesValue{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetAddresses() GetCache2XXResponseDnsCacheEntriesValueAddresses {
	if o == nil || IsNil(o.Addresses) {
		var ret GetCache2XXResponseDnsCacheEntriesValueAddresses
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetAddressesOk() (*GetCache2XXResponseDnsCacheEntriesValueAddresses, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given GetCache2XXResponseDnsCacheEntriesValueAddresses and assigns it to the Addresses field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetAddresses(v GetCache2XXResponseDnsCacheEntriesValueAddresses) {
	o.Addresses = &v
}

// GetActiveAddress returns the ActiveAddress field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetActiveAddress() string {
	if o == nil || IsNil(o.ActiveAddress) {
		var ret string
		return ret
	}
	return *o.ActiveAddress
}

// GetActiveAddressOk returns a tuple with the ActiveAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetActiveAddressOk() (*string, bool) {
	if o == nil || IsNil(o.ActiveAddress) {
		return nil, false
	}
	return o.ActiveAddress, true
}

// HasActiveAddress returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasActiveAddress() bool {
	if o != nil && !IsNil(o.ActiveAddress) {
		return true
	}

	return false
}

// SetActiveAddress gets a reference to the given string and assigns it to the ActiveAddress field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetActiveAddress(v string) {
	o.ActiveAddress = &v
}

// GetFamily returns the Family field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetFamily() float32 {
	if o == nil || IsNil(o.Family) {
		var ret float32
		return ret
	}
	return *o.Family
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetFamilyOk() (*float32, bool) {
	if o == nil || IsNil(o.Family) {
		return nil, false
	}
	return o.Family, true
}

// HasFamily returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasFamily() bool {
	if o != nil && !IsNil(o.Family) {
		return true
	}

	return false
}

// SetFamily gets a reference to the given float32 and assigns it to the Family field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetFamily(v float32) {
	o.Family = &v
}

// GetAge returns the Age field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetAge() float32 {
	if o == nil || IsNil(o.Age) {
		var ret float32
		return ret
	}
	return *o.Age
}

// GetAgeOk returns a tuple with the Age field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetAgeOk() (*float32, bool) {
	if o == nil || IsNil(o.Age) {
		return nil, false
	}
	return o.Age, true
}

// HasAge returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasAge() bool {
	if o != nil && !IsNil(o.Age) {
		return true
	}

	return false
}

// SetAge gets a reference to the given float32 and assigns it to the Age field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetAge(v float32) {
	o.Age = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetTtl() float32 {
	if o == nil || IsNil(o.Ttl) {
		var ret float32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetTtlOk() (*float32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given float32 and assigns it to the Ttl field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetTtl(v float32) {
	o.Ttl = &v
}

// GetNetworkErrors returns the NetworkErrors field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetNetworkErrors() float32 {
	if o == nil || IsNil(o.NetworkErrors) {
		var ret float32
		return ret
	}
	return *o.NetworkErrors
}

// GetNetworkErrorsOk returns a tuple with the NetworkErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetNetworkErrorsOk() (*float32, bool) {
	if o == nil || IsNil(o.NetworkErrors) {
		return nil, false
	}
	return o.NetworkErrors, true
}

// HasNetworkErrors returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasNetworkErrors() bool {
	if o != nil && !IsNil(o.NetworkErrors) {
		return true
	}

	return false
}

// SetNetworkErrors gets a reference to the given float32 and assigns it to the NetworkErrors field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetNetworkErrors(v float32) {
	o.NetworkErrors = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetHits() float32 {
	if o == nil || IsNil(o.Hits) {
		var ret float32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetHitsOk() (*float32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given float32 and assigns it to the Hits field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetHits(v float32) {
	o.Hits = &v
}

// GetMisses returns the Misses field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetMisses() float32 {
	if o == nil || IsNil(o.Misses) {
		var ret float32
		return ret
	}
	return *o.Misses
}

// GetMissesOk returns a tuple with the Misses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) GetMissesOk() (*float32, bool) {
	if o == nil || IsNil(o.Misses) {
		return nil, false
	}
	return o.Misses, true
}

// HasMisses returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValue) HasMisses() bool {
	if o != nil && !IsNil(o.Misses) {
		return true
	}

	return false
}

// SetMisses gets a reference to the given float32 and assigns it to the Misses field.
func (o *GetCache2XXResponseDnsCacheEntriesValue) SetMisses(v float32) {
	o.Misses = &v
}

func (o GetCache2XXResponseDnsCacheEntriesValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCache2XXResponseDnsCacheEntriesValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.ActiveAddress) {
		toSerialize["activeAddress"] = o.ActiveAddress
	}
	if !IsNil(o.Family) {
		toSerialize["family"] = o.Family
	}
	if !IsNil(o.Age) {
		toSerialize["age"] = o.Age
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !IsNil(o.NetworkErrors) {
		toSerialize["networkErrors"] = o.NetworkErrors
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.Misses) {
		toSerialize["misses"] = o.Misses
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCache2XXResponseDnsCacheEntriesValue) UnmarshalJSON(data []byte) (err error) {
	varGetCache2XXResponseDnsCacheEntriesValue := _GetCache2XXResponseDnsCacheEntriesValue{}

	err = json.Unmarshal(data, &varGetCache2XXResponseDnsCacheEntriesValue)

	if err != nil {
		return err
	}

	*o = GetCache2XXResponseDnsCacheEntriesValue(varGetCache2XXResponseDnsCacheEntriesValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "addresses")
		delete(additionalProperties, "activeAddress")
		delete(additionalProperties, "family")
		delete(additionalProperties, "age")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "networkErrors")
		delete(additionalProperties, "hits")
		delete(additionalProperties, "misses")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCache2XXResponseDnsCacheEntriesValue struct {
	value *GetCache2XXResponseDnsCacheEntriesValue
	isSet bool
}

func (v NullableGetCache2XXResponseDnsCacheEntriesValue) Get() *GetCache2XXResponseDnsCacheEntriesValue {
	return v.value
}

func (v *NullableGetCache2XXResponseDnsCacheEntriesValue) Set(val *GetCache2XXResponseDnsCacheEntriesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCache2XXResponseDnsCacheEntriesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCache2XXResponseDnsCacheEntriesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCache2XXResponseDnsCacheEntriesValue(val *GetCache2XXResponseDnsCacheEntriesValue) *NullableGetCache2XXResponseDnsCacheEntriesValue {
	return &NullableGetCache2XXResponseDnsCacheEntriesValue{value: val, isSet: true}
}

func (v NullableGetCache2XXResponseDnsCacheEntriesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCache2XXResponseDnsCacheEntriesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


