/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the TestMetadatasRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestMetadatasRequest{}

// TestMetadatasRequest struct for TestMetadatasRequest
type TestMetadatasRequest struct {
	Tmdb *bool `json:"tmdb,omitempty"`
	Tvdb *bool `json:"tvdb,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TestMetadatasRequest TestMetadatasRequest

// NewTestMetadatasRequest instantiates a new TestMetadatasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestMetadatasRequest() *TestMetadatasRequest {
	this := TestMetadatasRequest{}
	return &this
}

// NewTestMetadatasRequestWithDefaults instantiates a new TestMetadatasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestMetadatasRequestWithDefaults() *TestMetadatasRequest {
	this := TestMetadatasRequest{}
	return &this
}

// GetTmdb returns the Tmdb field value if set, zero value otherwise.
func (o *TestMetadatasRequest) GetTmdb() bool {
	if o == nil || IsNil(o.Tmdb) {
		var ret bool
		return ret
	}
	return *o.Tmdb
}

// GetTmdbOk returns a tuple with the Tmdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestMetadatasRequest) GetTmdbOk() (*bool, bool) {
	if o == nil || IsNil(o.Tmdb) {
		return nil, false
	}
	return o.Tmdb, true
}

// HasTmdb returns a boolean if a field has been set.
func (o *TestMetadatasRequest) HasTmdb() bool {
	if o != nil && !IsNil(o.Tmdb) {
		return true
	}

	return false
}

// SetTmdb gets a reference to the given bool and assigns it to the Tmdb field.
func (o *TestMetadatasRequest) SetTmdb(v bool) {
	o.Tmdb = &v
}

// GetTvdb returns the Tvdb field value if set, zero value otherwise.
func (o *TestMetadatasRequest) GetTvdb() bool {
	if o == nil || IsNil(o.Tvdb) {
		var ret bool
		return ret
	}
	return *o.Tvdb
}

// GetTvdbOk returns a tuple with the Tvdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestMetadatasRequest) GetTvdbOk() (*bool, bool) {
	if o == nil || IsNil(o.Tvdb) {
		return nil, false
	}
	return o.Tvdb, true
}

// HasTvdb returns a boolean if a field has been set.
func (o *TestMetadatasRequest) HasTvdb() bool {
	if o != nil && !IsNil(o.Tvdb) {
		return true
	}

	return false
}

// SetTvdb gets a reference to the given bool and assigns it to the Tvdb field.
func (o *TestMetadatasRequest) SetTvdb(v bool) {
	o.Tvdb = &v
}

func (o TestMetadatasRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestMetadatasRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tmdb) {
		toSerialize["tmdb"] = o.Tmdb
	}
	if !IsNil(o.Tvdb) {
		toSerialize["tvdb"] = o.Tvdb
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TestMetadatasRequest) UnmarshalJSON(data []byte) (err error) {
	varTestMetadatasRequest := _TestMetadatasRequest{}

	err = json.Unmarshal(data, &varTestMetadatasRequest)

	if err != nil {
		return err
	}

	*o = TestMetadatasRequest(varTestMetadatasRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tmdb")
		delete(additionalProperties, "tvdb")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestMetadatasRequest struct {
	value *TestMetadatasRequest
	isSet bool
}

func (v NullableTestMetadatasRequest) Get() *TestMetadatasRequest {
	return v.value
}

func (v *NullableTestMetadatasRequest) Set(val *TestMetadatasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTestMetadatasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTestMetadatasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestMetadatasRequest(val *TestMetadatasRequest) *NullableTestMetadatasRequest {
	return &NullableTestMetadatasRequest{value: val, isSet: true}
}

func (v NullableTestMetadatasRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestMetadatasRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


