/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateJellyfinLibraryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateJellyfinLibraryRequest{}

// UpdateJellyfinLibraryRequest struct for UpdateJellyfinLibraryRequest
type UpdateJellyfinLibraryRequest struct {
	Enabled bool `json:"enabled"`
	AdditionalProperties map[string]interface{}
}

type _UpdateJellyfinLibraryRequest UpdateJellyfinLibraryRequest

// NewUpdateJellyfinLibraryRequest instantiates a new UpdateJellyfinLibraryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateJellyfinLibraryRequest(enabled bool) *UpdateJellyfinLibraryRequest {
	this := UpdateJellyfinLibraryRequest{}
	this.Enabled = enabled
	return &this
}

// NewUpdateJellyfinLibraryRequestWithDefaults instantiates a new UpdateJellyfinLibraryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateJellyfinLibraryRequestWithDefaults() *UpdateJellyfinLibraryRequest {
	this := UpdateJellyfinLibraryRequest{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *UpdateJellyfinLibraryRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *UpdateJellyfinLibraryRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *UpdateJellyfinLibraryRequest) SetEnabled(v bool) {
	o.Enabled = v
}

func (o UpdateJellyfinLibraryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateJellyfinLibraryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateJellyfinLibraryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateJellyfinLibraryRequest := _UpdateJellyfinLibraryRequest{}

	err = json.Unmarshal(data, &varUpdateJellyfinLibraryRequest)

	if err != nil {
		return err
	}

	*o = UpdateJellyfinLibraryRequest(varUpdateJellyfinLibraryRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateJellyfinLibraryRequest struct {
	value *UpdateJellyfinLibraryRequest
	isSet bool
}

func (v NullableUpdateJellyfinLibraryRequest) Get() *UpdateJellyfinLibraryRequest {
	return v.value
}

func (v *NullableUpdateJellyfinLibraryRequest) Set(val *UpdateJellyfinLibraryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateJellyfinLibraryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateJellyfinLibraryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateJellyfinLibraryRequest(val *UpdateJellyfinLibraryRequest) *NullableUpdateJellyfinLibraryRequest {
	return &NullableUpdateJellyfinLibraryRequest{value: val, isSet: true}
}

func (v NullableUpdateJellyfinLibraryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateJellyfinLibraryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


