/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetKeywordByKeywordId500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetKeywordByKeywordId500Response{}

// GetKeywordByKeywordId500Response struct for GetKeywordByKeywordId500Response
type GetKeywordByKeywordId500Response struct {
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetKeywordByKeywordId500Response GetKeywordByKeywordId500Response

// NewGetKeywordByKeywordId500Response instantiates a new GetKeywordByKeywordId500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetKeywordByKeywordId500Response() *GetKeywordByKeywordId500Response {
	this := GetKeywordByKeywordId500Response{}
	return &this
}

// NewGetKeywordByKeywordId500ResponseWithDefaults instantiates a new GetKeywordByKeywordId500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetKeywordByKeywordId500ResponseWithDefaults() *GetKeywordByKeywordId500Response {
	this := GetKeywordByKeywordId500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetKeywordByKeywordId500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKeywordByKeywordId500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetKeywordByKeywordId500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetKeywordByKeywordId500Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetKeywordByKeywordId500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetKeywordByKeywordId500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetKeywordByKeywordId500Response) UnmarshalJSON(data []byte) (err error) {
	varGetKeywordByKeywordId500Response := _GetKeywordByKeywordId500Response{}

	err = json.Unmarshal(data, &varGetKeywordByKeywordId500Response)

	if err != nil {
		return err
	}

	*o = GetKeywordByKeywordId500Response(varGetKeywordByKeywordId500Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetKeywordByKeywordId500Response struct {
	value *GetKeywordByKeywordId500Response
	isSet bool
}

func (v NullableGetKeywordByKeywordId500Response) Get() *GetKeywordByKeywordId500Response {
	return v.value
}

func (v *NullableGetKeywordByKeywordId500Response) Set(val *GetKeywordByKeywordId500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetKeywordByKeywordId500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetKeywordByKeywordId500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetKeywordByKeywordId500Response(val *GetKeywordByKeywordId500Response) *NullableGetKeywordByKeywordId500Response {
	return &NullableGetKeywordByKeywordId500Response{value: val, isSet: true}
}

func (v NullableGetKeywordByKeywordId500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetKeywordByKeywordId500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


