/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetCache2XXResponseDnsCacheStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCache2XXResponseDnsCacheStats{}

// GetCache2XXResponseDnsCacheStats struct for GetCache2XXResponseDnsCacheStats
type GetCache2XXResponseDnsCacheStats struct {
	Size *float32 `json:"size,omitempty"`
	MaxSize *float32 `json:"maxSize,omitempty"`
	Hits *float32 `json:"hits,omitempty"`
	Misses *float32 `json:"misses,omitempty"`
	Failures *float32 `json:"failures,omitempty"`
	Ipv4Fallbacks *float32 `json:"ipv4Fallbacks,omitempty"`
	HitRate *float32 `json:"hitRate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCache2XXResponseDnsCacheStats GetCache2XXResponseDnsCacheStats

// NewGetCache2XXResponseDnsCacheStats instantiates a new GetCache2XXResponseDnsCacheStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCache2XXResponseDnsCacheStats() *GetCache2XXResponseDnsCacheStats {
	this := GetCache2XXResponseDnsCacheStats{}
	return &this
}

// NewGetCache2XXResponseDnsCacheStatsWithDefaults instantiates a new GetCache2XXResponseDnsCacheStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCache2XXResponseDnsCacheStatsWithDefaults() *GetCache2XXResponseDnsCacheStats {
	this := GetCache2XXResponseDnsCacheStats{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetSize() float32 {
	if o == nil || IsNil(o.Size) {
		var ret float32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given float32 and assigns it to the Size field.
func (o *GetCache2XXResponseDnsCacheStats) SetSize(v float32) {
	o.Size = &v
}

// GetMaxSize returns the MaxSize field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetMaxSize() float32 {
	if o == nil || IsNil(o.MaxSize) {
		var ret float32
		return ret
	}
	return *o.MaxSize
}

// GetMaxSizeOk returns a tuple with the MaxSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetMaxSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxSize) {
		return nil, false
	}
	return o.MaxSize, true
}

// HasMaxSize returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasMaxSize() bool {
	if o != nil && !IsNil(o.MaxSize) {
		return true
	}

	return false
}

// SetMaxSize gets a reference to the given float32 and assigns it to the MaxSize field.
func (o *GetCache2XXResponseDnsCacheStats) SetMaxSize(v float32) {
	o.MaxSize = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetHits() float32 {
	if o == nil || IsNil(o.Hits) {
		var ret float32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetHitsOk() (*float32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given float32 and assigns it to the Hits field.
func (o *GetCache2XXResponseDnsCacheStats) SetHits(v float32) {
	o.Hits = &v
}

// GetMisses returns the Misses field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetMisses() float32 {
	if o == nil || IsNil(o.Misses) {
		var ret float32
		return ret
	}
	return *o.Misses
}

// GetMissesOk returns a tuple with the Misses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetMissesOk() (*float32, bool) {
	if o == nil || IsNil(o.Misses) {
		return nil, false
	}
	return o.Misses, true
}

// HasMisses returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasMisses() bool {
	if o != nil && !IsNil(o.Misses) {
		return true
	}

	return false
}

// SetMisses gets a reference to the given float32 and assigns it to the Misses field.
func (o *GetCache2XXResponseDnsCacheStats) SetMisses(v float32) {
	o.Misses = &v
}

// GetFailures returns the Failures field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetFailures() float32 {
	if o == nil || IsNil(o.Failures) {
		var ret float32
		return ret
	}
	return *o.Failures
}

// GetFailuresOk returns a tuple with the Failures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetFailuresOk() (*float32, bool) {
	if o == nil || IsNil(o.Failures) {
		return nil, false
	}
	return o.Failures, true
}

// HasFailures returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasFailures() bool {
	if o != nil && !IsNil(o.Failures) {
		return true
	}

	return false
}

// SetFailures gets a reference to the given float32 and assigns it to the Failures field.
func (o *GetCache2XXResponseDnsCacheStats) SetFailures(v float32) {
	o.Failures = &v
}

// GetIpv4Fallbacks returns the Ipv4Fallbacks field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetIpv4Fallbacks() float32 {
	if o == nil || IsNil(o.Ipv4Fallbacks) {
		var ret float32
		return ret
	}
	return *o.Ipv4Fallbacks
}

// GetIpv4FallbacksOk returns a tuple with the Ipv4Fallbacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetIpv4FallbacksOk() (*float32, bool) {
	if o == nil || IsNil(o.Ipv4Fallbacks) {
		return nil, false
	}
	return o.Ipv4Fallbacks, true
}

// HasIpv4Fallbacks returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasIpv4Fallbacks() bool {
	if o != nil && !IsNil(o.Ipv4Fallbacks) {
		return true
	}

	return false
}

// SetIpv4Fallbacks gets a reference to the given float32 and assigns it to the Ipv4Fallbacks field.
func (o *GetCache2XXResponseDnsCacheStats) SetIpv4Fallbacks(v float32) {
	o.Ipv4Fallbacks = &v
}

// GetHitRate returns the HitRate field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheStats) GetHitRate() float32 {
	if o == nil || IsNil(o.HitRate) {
		var ret float32
		return ret
	}
	return *o.HitRate
}

// GetHitRateOk returns a tuple with the HitRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheStats) GetHitRateOk() (*float32, bool) {
	if o == nil || IsNil(o.HitRate) {
		return nil, false
	}
	return o.HitRate, true
}

// HasHitRate returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheStats) HasHitRate() bool {
	if o != nil && !IsNil(o.HitRate) {
		return true
	}

	return false
}

// SetHitRate gets a reference to the given float32 and assigns it to the HitRate field.
func (o *GetCache2XXResponseDnsCacheStats) SetHitRate(v float32) {
	o.HitRate = &v
}

func (o GetCache2XXResponseDnsCacheStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCache2XXResponseDnsCacheStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.MaxSize) {
		toSerialize["maxSize"] = o.MaxSize
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.Misses) {
		toSerialize["misses"] = o.Misses
	}
	if !IsNil(o.Failures) {
		toSerialize["failures"] = o.Failures
	}
	if !IsNil(o.Ipv4Fallbacks) {
		toSerialize["ipv4Fallbacks"] = o.Ipv4Fallbacks
	}
	if !IsNil(o.HitRate) {
		toSerialize["hitRate"] = o.HitRate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCache2XXResponseDnsCacheStats) UnmarshalJSON(data []byte) (err error) {
	varGetCache2XXResponseDnsCacheStats := _GetCache2XXResponseDnsCacheStats{}

	err = json.Unmarshal(data, &varGetCache2XXResponseDnsCacheStats)

	if err != nil {
		return err
	}

	*o = GetCache2XXResponseDnsCacheStats(varGetCache2XXResponseDnsCacheStats)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "size")
		delete(additionalProperties, "maxSize")
		delete(additionalProperties, "hits")
		delete(additionalProperties, "misses")
		delete(additionalProperties, "failures")
		delete(additionalProperties, "ipv4Fallbacks")
		delete(additionalProperties, "hitRate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCache2XXResponseDnsCacheStats struct {
	value *GetCache2XXResponseDnsCacheStats
	isSet bool
}

func (v NullableGetCache2XXResponseDnsCacheStats) Get() *GetCache2XXResponseDnsCacheStats {
	return v.value
}

func (v *NullableGetCache2XXResponseDnsCacheStats) Set(val *GetCache2XXResponseDnsCacheStats) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCache2XXResponseDnsCacheStats) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCache2XXResponseDnsCacheStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCache2XXResponseDnsCacheStats(val *GetCache2XXResponseDnsCacheStats) *NullableGetCache2XXResponseDnsCacheStats {
	return &NullableGetCache2XXResponseDnsCacheStats{value: val, isSet: true}
}

func (v NullableGetCache2XXResponseDnsCacheStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCache2XXResponseDnsCacheStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


