/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the CreateOverrideruleAdvancedRequest2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOverrideruleAdvancedRequest2XXResponse{}

// CreateOverrideruleAdvancedRequest2XXResponse struct for CreateOverrideruleAdvancedRequest2XXResponse
type CreateOverrideruleAdvancedRequest2XXResponse struct {
	RootFolder NullableString `json:"rootFolder,omitempty"`
	ProfileId NullableFloat32 `json:"profileId,omitempty"`
	Tags []float32 `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOverrideruleAdvancedRequest2XXResponse CreateOverrideruleAdvancedRequest2XXResponse

// NewCreateOverrideruleAdvancedRequest2XXResponse instantiates a new CreateOverrideruleAdvancedRequest2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOverrideruleAdvancedRequest2XXResponse() *CreateOverrideruleAdvancedRequest2XXResponse {
	this := CreateOverrideruleAdvancedRequest2XXResponse{}
	return &this
}

// NewCreateOverrideruleAdvancedRequest2XXResponseWithDefaults instantiates a new CreateOverrideruleAdvancedRequest2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOverrideruleAdvancedRequest2XXResponseWithDefaults() *CreateOverrideruleAdvancedRequest2XXResponse {
	this := CreateOverrideruleAdvancedRequest2XXResponse{}
	return &this
}

// GetRootFolder returns the RootFolder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequest2XXResponse) GetRootFolder() string {
	if o == nil || IsNil(o.RootFolder.Get()) {
		var ret string
		return ret
	}
	return *o.RootFolder.Get()
}

// GetRootFolderOk returns a tuple with the RootFolder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequest2XXResponse) GetRootFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RootFolder.Get(), o.RootFolder.IsSet()
}

// HasRootFolder returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequest2XXResponse) HasRootFolder() bool {
	if o != nil && o.RootFolder.IsSet() {
		return true
	}

	return false
}

// SetRootFolder gets a reference to the given NullableString and assigns it to the RootFolder field.
func (o *CreateOverrideruleAdvancedRequest2XXResponse) SetRootFolder(v string) {
	o.RootFolder.Set(&v)
}
// SetRootFolderNil sets the value for RootFolder to be an explicit nil
func (o *CreateOverrideruleAdvancedRequest2XXResponse) SetRootFolderNil() {
	o.RootFolder.Set(nil)
}

// UnsetRootFolder ensures that no value is present for RootFolder, not even an explicit nil
func (o *CreateOverrideruleAdvancedRequest2XXResponse) UnsetRootFolder() {
	o.RootFolder.Unset()
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequest2XXResponse) GetProfileId() float32 {
	if o == nil || IsNil(o.ProfileId.Get()) {
		var ret float32
		return ret
	}
	return *o.ProfileId.Get()
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequest2XXResponse) GetProfileIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileId.Get(), o.ProfileId.IsSet()
}

// HasProfileId returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequest2XXResponse) HasProfileId() bool {
	if o != nil && o.ProfileId.IsSet() {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given NullableFloat32 and assigns it to the ProfileId field.
func (o *CreateOverrideruleAdvancedRequest2XXResponse) SetProfileId(v float32) {
	o.ProfileId.Set(&v)
}
// SetProfileIdNil sets the value for ProfileId to be an explicit nil
func (o *CreateOverrideruleAdvancedRequest2XXResponse) SetProfileIdNil() {
	o.ProfileId.Set(nil)
}

// UnsetProfileId ensures that no value is present for ProfileId, not even an explicit nil
func (o *CreateOverrideruleAdvancedRequest2XXResponse) UnsetProfileId() {
	o.ProfileId.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequest2XXResponse) GetTags() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequest2XXResponse) GetTagsOk() ([]float32, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequest2XXResponse) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []float32 and assigns it to the Tags field.
func (o *CreateOverrideruleAdvancedRequest2XXResponse) SetTags(v []float32) {
	o.Tags = v
}

func (o CreateOverrideruleAdvancedRequest2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOverrideruleAdvancedRequest2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RootFolder.IsSet() {
		toSerialize["rootFolder"] = o.RootFolder.Get()
	}
	if o.ProfileId.IsSet() {
		toSerialize["profileId"] = o.ProfileId.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOverrideruleAdvancedRequest2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateOverrideruleAdvancedRequest2XXResponse := _CreateOverrideruleAdvancedRequest2XXResponse{}

	err = json.Unmarshal(data, &varCreateOverrideruleAdvancedRequest2XXResponse)

	if err != nil {
		return err
	}

	*o = CreateOverrideruleAdvancedRequest2XXResponse(varCreateOverrideruleAdvancedRequest2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rootFolder")
		delete(additionalProperties, "profileId")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOverrideruleAdvancedRequest2XXResponse struct {
	value *CreateOverrideruleAdvancedRequest2XXResponse
	isSet bool
}

func (v NullableCreateOverrideruleAdvancedRequest2XXResponse) Get() *CreateOverrideruleAdvancedRequest2XXResponse {
	return v.value
}

func (v *NullableCreateOverrideruleAdvancedRequest2XXResponse) Set(val *CreateOverrideruleAdvancedRequest2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOverrideruleAdvancedRequest2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOverrideruleAdvancedRequest2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOverrideruleAdvancedRequest2XXResponse(val *CreateOverrideruleAdvancedRequest2XXResponse) *NullableCreateOverrideruleAdvancedRequest2XXResponse {
	return &NullableCreateOverrideruleAdvancedRequest2XXResponse{value: val, isSet: true}
}

func (v NullableCreateOverrideruleAdvancedRequest2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOverrideruleAdvancedRequest2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


