/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the CreateAuthJellyfinQuickconnectInitiate2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAuthJellyfinQuickconnectInitiate2XXResponse{}

// CreateAuthJellyfinQuickconnectInitiate2XXResponse struct for CreateAuthJellyfinQuickconnectInitiate2XXResponse
type CreateAuthJellyfinQuickconnectInitiate2XXResponse struct {
	Code *string `json:"code,omitempty"`
	Secret *string `json:"secret,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAuthJellyfinQuickconnectInitiate2XXResponse CreateAuthJellyfinQuickconnectInitiate2XXResponse

// NewCreateAuthJellyfinQuickconnectInitiate2XXResponse instantiates a new CreateAuthJellyfinQuickconnectInitiate2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAuthJellyfinQuickconnectInitiate2XXResponse() *CreateAuthJellyfinQuickconnectInitiate2XXResponse {
	this := CreateAuthJellyfinQuickconnectInitiate2XXResponse{}
	return &this
}

// NewCreateAuthJellyfinQuickconnectInitiate2XXResponseWithDefaults instantiates a new CreateAuthJellyfinQuickconnectInitiate2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAuthJellyfinQuickconnectInitiate2XXResponseWithDefaults() *CreateAuthJellyfinQuickconnectInitiate2XXResponse {
	this := CreateAuthJellyfinQuickconnectInitiate2XXResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) SetCode(v string) {
	o.Code = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) SetSecret(v string) {
	o.Secret = &v
}

func (o CreateAuthJellyfinQuickconnectInitiate2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAuthJellyfinQuickconnectInitiate2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAuthJellyfinQuickconnectInitiate2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateAuthJellyfinQuickconnectInitiate2XXResponse := _CreateAuthJellyfinQuickconnectInitiate2XXResponse{}

	err = json.Unmarshal(data, &varCreateAuthJellyfinQuickconnectInitiate2XXResponse)

	if err != nil {
		return err
	}

	*o = CreateAuthJellyfinQuickconnectInitiate2XXResponse(varCreateAuthJellyfinQuickconnectInitiate2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "secret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse struct {
	value *CreateAuthJellyfinQuickconnectInitiate2XXResponse
	isSet bool
}

func (v NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse) Get() *CreateAuthJellyfinQuickconnectInitiate2XXResponse {
	return v.value
}

func (v *NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse) Set(val *CreateAuthJellyfinQuickconnectInitiate2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAuthJellyfinQuickconnectInitiate2XXResponse(val *CreateAuthJellyfinQuickconnectInitiate2XXResponse) *NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse {
	return &NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse{value: val, isSet: true}
}

func (v NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAuthJellyfinQuickconnectInitiate2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


