/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateOverrideruleAdvancedRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOverrideruleAdvancedRequestRequest{}

// CreateOverrideruleAdvancedRequestRequest struct for CreateOverrideruleAdvancedRequestRequest
type CreateOverrideruleAdvancedRequestRequest struct {
	MediaType string `json:"mediaType"`
	TmdbId float32 `json:"tmdbId"`
	Is4k *bool `json:"is4k,omitempty"`
	RequestId NullableFloat32 `json:"requestId,omitempty"`
	RequestUser NullableFloat32 `json:"requestUser,omitempty"`
	Tags []float32 `json:"tags,omitempty"`
	ServiceId NullableFloat32 `json:"serviceId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOverrideruleAdvancedRequestRequest CreateOverrideruleAdvancedRequestRequest

// NewCreateOverrideruleAdvancedRequestRequest instantiates a new CreateOverrideruleAdvancedRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOverrideruleAdvancedRequestRequest(mediaType string, tmdbId float32) *CreateOverrideruleAdvancedRequestRequest {
	this := CreateOverrideruleAdvancedRequestRequest{}
	this.MediaType = mediaType
	this.TmdbId = tmdbId
	return &this
}

// NewCreateOverrideruleAdvancedRequestRequestWithDefaults instantiates a new CreateOverrideruleAdvancedRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOverrideruleAdvancedRequestRequestWithDefaults() *CreateOverrideruleAdvancedRequestRequest {
	this := CreateOverrideruleAdvancedRequestRequest{}
	return &this
}

// GetMediaType returns the MediaType field value
func (o *CreateOverrideruleAdvancedRequestRequest) GetMediaType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value
// and a boolean to check if the value has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) GetMediaTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaType, true
}

// SetMediaType sets field value
func (o *CreateOverrideruleAdvancedRequestRequest) SetMediaType(v string) {
	o.MediaType = v
}

// GetTmdbId returns the TmdbId field value
func (o *CreateOverrideruleAdvancedRequestRequest) GetTmdbId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TmdbId
}

// GetTmdbIdOk returns a tuple with the TmdbId field value
// and a boolean to check if the value has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) GetTmdbIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TmdbId, true
}

// SetTmdbId sets field value
func (o *CreateOverrideruleAdvancedRequestRequest) SetTmdbId(v float32) {
	o.TmdbId = v
}

// GetIs4k returns the Is4k field value if set, zero value otherwise.
func (o *CreateOverrideruleAdvancedRequestRequest) GetIs4k() bool {
	if o == nil || IsNil(o.Is4k) {
		var ret bool
		return ret
	}
	return *o.Is4k
}

// GetIs4kOk returns a tuple with the Is4k field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) GetIs4kOk() (*bool, bool) {
	if o == nil || IsNil(o.Is4k) {
		return nil, false
	}
	return o.Is4k, true
}

// HasIs4k returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) HasIs4k() bool {
	if o != nil && !IsNil(o.Is4k) {
		return true
	}

	return false
}

// SetIs4k gets a reference to the given bool and assigns it to the Is4k field.
func (o *CreateOverrideruleAdvancedRequestRequest) SetIs4k(v bool) {
	o.Is4k = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequestRequest) GetRequestId() float32 {
	if o == nil || IsNil(o.RequestId.Get()) {
		var ret float32
		return ret
	}
	return *o.RequestId.Get()
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequestRequest) GetRequestIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestId.Get(), o.RequestId.IsSet()
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) HasRequestId() bool {
	if o != nil && o.RequestId.IsSet() {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given NullableFloat32 and assigns it to the RequestId field.
func (o *CreateOverrideruleAdvancedRequestRequest) SetRequestId(v float32) {
	o.RequestId.Set(&v)
}
// SetRequestIdNil sets the value for RequestId to be an explicit nil
func (o *CreateOverrideruleAdvancedRequestRequest) SetRequestIdNil() {
	o.RequestId.Set(nil)
}

// UnsetRequestId ensures that no value is present for RequestId, not even an explicit nil
func (o *CreateOverrideruleAdvancedRequestRequest) UnsetRequestId() {
	o.RequestId.Unset()
}

// GetRequestUser returns the RequestUser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequestRequest) GetRequestUser() float32 {
	if o == nil || IsNil(o.RequestUser.Get()) {
		var ret float32
		return ret
	}
	return *o.RequestUser.Get()
}

// GetRequestUserOk returns a tuple with the RequestUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequestRequest) GetRequestUserOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestUser.Get(), o.RequestUser.IsSet()
}

// HasRequestUser returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) HasRequestUser() bool {
	if o != nil && o.RequestUser.IsSet() {
		return true
	}

	return false
}

// SetRequestUser gets a reference to the given NullableFloat32 and assigns it to the RequestUser field.
func (o *CreateOverrideruleAdvancedRequestRequest) SetRequestUser(v float32) {
	o.RequestUser.Set(&v)
}
// SetRequestUserNil sets the value for RequestUser to be an explicit nil
func (o *CreateOverrideruleAdvancedRequestRequest) SetRequestUserNil() {
	o.RequestUser.Set(nil)
}

// UnsetRequestUser ensures that no value is present for RequestUser, not even an explicit nil
func (o *CreateOverrideruleAdvancedRequestRequest) UnsetRequestUser() {
	o.RequestUser.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequestRequest) GetTags() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequestRequest) GetTagsOk() ([]float32, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []float32 and assigns it to the Tags field.
func (o *CreateOverrideruleAdvancedRequestRequest) SetTags(v []float32) {
	o.Tags = v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOverrideruleAdvancedRequestRequest) GetServiceId() float32 {
	if o == nil || IsNil(o.ServiceId.Get()) {
		var ret float32
		return ret
	}
	return *o.ServiceId.Get()
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOverrideruleAdvancedRequestRequest) GetServiceIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceId.Get(), o.ServiceId.IsSet()
}

// HasServiceId returns a boolean if a field has been set.
func (o *CreateOverrideruleAdvancedRequestRequest) HasServiceId() bool {
	if o != nil && o.ServiceId.IsSet() {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given NullableFloat32 and assigns it to the ServiceId field.
func (o *CreateOverrideruleAdvancedRequestRequest) SetServiceId(v float32) {
	o.ServiceId.Set(&v)
}
// SetServiceIdNil sets the value for ServiceId to be an explicit nil
func (o *CreateOverrideruleAdvancedRequestRequest) SetServiceIdNil() {
	o.ServiceId.Set(nil)
}

// UnsetServiceId ensures that no value is present for ServiceId, not even an explicit nil
func (o *CreateOverrideruleAdvancedRequestRequest) UnsetServiceId() {
	o.ServiceId.Unset()
}

func (o CreateOverrideruleAdvancedRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOverrideruleAdvancedRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mediaType"] = o.MediaType
	toSerialize["tmdbId"] = o.TmdbId
	if !IsNil(o.Is4k) {
		toSerialize["is4k"] = o.Is4k
	}
	if o.RequestId.IsSet() {
		toSerialize["requestId"] = o.RequestId.Get()
	}
	if o.RequestUser.IsSet() {
		toSerialize["requestUser"] = o.RequestUser.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.ServiceId.IsSet() {
		toSerialize["serviceId"] = o.ServiceId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOverrideruleAdvancedRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mediaType",
		"tmdbId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOverrideruleAdvancedRequestRequest := _CreateOverrideruleAdvancedRequestRequest{}

	err = json.Unmarshal(data, &varCreateOverrideruleAdvancedRequestRequest)

	if err != nil {
		return err
	}

	*o = CreateOverrideruleAdvancedRequestRequest(varCreateOverrideruleAdvancedRequestRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mediaType")
		delete(additionalProperties, "tmdbId")
		delete(additionalProperties, "is4k")
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "requestUser")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "serviceId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOverrideruleAdvancedRequestRequest struct {
	value *CreateOverrideruleAdvancedRequestRequest
	isSet bool
}

func (v NullableCreateOverrideruleAdvancedRequestRequest) Get() *CreateOverrideruleAdvancedRequestRequest {
	return v.value
}

func (v *NullableCreateOverrideruleAdvancedRequestRequest) Set(val *CreateOverrideruleAdvancedRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOverrideruleAdvancedRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOverrideruleAdvancedRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOverrideruleAdvancedRequestRequest(val *CreateOverrideruleAdvancedRequestRequest) *NullableCreateOverrideruleAdvancedRequestRequest {
	return &NullableCreateOverrideruleAdvancedRequestRequest{value: val, isSet: true}
}

func (v NullableCreateOverrideruleAdvancedRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOverrideruleAdvancedRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


