/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetCache2XXResponseDnsCacheEntriesValueAddresses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCache2XXResponseDnsCacheEntriesValueAddresses{}

// GetCache2XXResponseDnsCacheEntriesValueAddresses struct for GetCache2XXResponseDnsCacheEntriesValueAddresses
type GetCache2XXResponseDnsCacheEntriesValueAddresses struct {
	Ipv4 *float32 `json:"ipv4,omitempty"`
	Ipv6 *float32 `json:"ipv6,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCache2XXResponseDnsCacheEntriesValueAddresses GetCache2XXResponseDnsCacheEntriesValueAddresses

// NewGetCache2XXResponseDnsCacheEntriesValueAddresses instantiates a new GetCache2XXResponseDnsCacheEntriesValueAddresses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCache2XXResponseDnsCacheEntriesValueAddresses() *GetCache2XXResponseDnsCacheEntriesValueAddresses {
	this := GetCache2XXResponseDnsCacheEntriesValueAddresses{}
	return &this
}

// NewGetCache2XXResponseDnsCacheEntriesValueAddressesWithDefaults instantiates a new GetCache2XXResponseDnsCacheEntriesValueAddresses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCache2XXResponseDnsCacheEntriesValueAddressesWithDefaults() *GetCache2XXResponseDnsCacheEntriesValueAddresses {
	this := GetCache2XXResponseDnsCacheEntriesValueAddresses{}
	return &this
}

// GetIpv4 returns the Ipv4 field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) GetIpv4() float32 {
	if o == nil || IsNil(o.Ipv4) {
		var ret float32
		return ret
	}
	return *o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) GetIpv4Ok() (*float32, bool) {
	if o == nil || IsNil(o.Ipv4) {
		return nil, false
	}
	return o.Ipv4, true
}

// HasIpv4 returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) HasIpv4() bool {
	if o != nil && !IsNil(o.Ipv4) {
		return true
	}

	return false
}

// SetIpv4 gets a reference to the given float32 and assigns it to the Ipv4 field.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) SetIpv4(v float32) {
	o.Ipv4 = &v
}

// GetIpv6 returns the Ipv6 field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) GetIpv6() float32 {
	if o == nil || IsNil(o.Ipv6) {
		var ret float32
		return ret
	}
	return *o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) GetIpv6Ok() (*float32, bool) {
	if o == nil || IsNil(o.Ipv6) {
		return nil, false
	}
	return o.Ipv6, true
}

// HasIpv6 returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) HasIpv6() bool {
	if o != nil && !IsNil(o.Ipv6) {
		return true
	}

	return false
}

// SetIpv6 gets a reference to the given float32 and assigns it to the Ipv6 field.
func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) SetIpv6(v float32) {
	o.Ipv6 = &v
}

func (o GetCache2XXResponseDnsCacheEntriesValueAddresses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCache2XXResponseDnsCacheEntriesValueAddresses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ipv4) {
		toSerialize["ipv4"] = o.Ipv4
	}
	if !IsNil(o.Ipv6) {
		toSerialize["ipv6"] = o.Ipv6
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCache2XXResponseDnsCacheEntriesValueAddresses) UnmarshalJSON(data []byte) (err error) {
	varGetCache2XXResponseDnsCacheEntriesValueAddresses := _GetCache2XXResponseDnsCacheEntriesValueAddresses{}

	err = json.Unmarshal(data, &varGetCache2XXResponseDnsCacheEntriesValueAddresses)

	if err != nil {
		return err
	}

	*o = GetCache2XXResponseDnsCacheEntriesValueAddresses(varGetCache2XXResponseDnsCacheEntriesValueAddresses)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ipv4")
		delete(additionalProperties, "ipv6")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCache2XXResponseDnsCacheEntriesValueAddresses struct {
	value *GetCache2XXResponseDnsCacheEntriesValueAddresses
	isSet bool
}

func (v NullableGetCache2XXResponseDnsCacheEntriesValueAddresses) Get() *GetCache2XXResponseDnsCacheEntriesValueAddresses {
	return v.value
}

func (v *NullableGetCache2XXResponseDnsCacheEntriesValueAddresses) Set(val *GetCache2XXResponseDnsCacheEntriesValueAddresses) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCache2XXResponseDnsCacheEntriesValueAddresses) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCache2XXResponseDnsCacheEntriesValueAddresses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCache2XXResponseDnsCacheEntriesValueAddresses(val *GetCache2XXResponseDnsCacheEntriesValueAddresses) *NullableGetCache2XXResponseDnsCacheEntriesValueAddresses {
	return &NullableGetCache2XXResponseDnsCacheEntriesValueAddresses{value: val, isSet: true}
}

func (v NullableGetCache2XXResponseDnsCacheEntriesValueAddresses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCache2XXResponseDnsCacheEntriesValueAddresses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


