/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
)

// checks if the GetCache2XXResponseDnsCache type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCache2XXResponseDnsCache{}

// GetCache2XXResponseDnsCache struct for GetCache2XXResponseDnsCache
type GetCache2XXResponseDnsCache struct {
	Stats *GetCache2XXResponseDnsCacheStats `json:"stats,omitempty"`
	Entries *map[string]GetCache2XXResponseDnsCacheEntriesValue `json:"entries,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCache2XXResponseDnsCache GetCache2XXResponseDnsCache

// NewGetCache2XXResponseDnsCache instantiates a new GetCache2XXResponseDnsCache object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCache2XXResponseDnsCache() *GetCache2XXResponseDnsCache {
	this := GetCache2XXResponseDnsCache{}
	return &this
}

// NewGetCache2XXResponseDnsCacheWithDefaults instantiates a new GetCache2XXResponseDnsCache object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCache2XXResponseDnsCacheWithDefaults() *GetCache2XXResponseDnsCache {
	this := GetCache2XXResponseDnsCache{}
	return &this
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCache) GetStats() GetCache2XXResponseDnsCacheStats {
	if o == nil || IsNil(o.Stats) {
		var ret GetCache2XXResponseDnsCacheStats
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCache) GetStatsOk() (*GetCache2XXResponseDnsCacheStats, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCache) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given GetCache2XXResponseDnsCacheStats and assigns it to the Stats field.
func (o *GetCache2XXResponseDnsCache) SetStats(v GetCache2XXResponseDnsCacheStats) {
	o.Stats = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *GetCache2XXResponseDnsCache) GetEntries() map[string]GetCache2XXResponseDnsCacheEntriesValue {
	if o == nil || IsNil(o.Entries) {
		var ret map[string]GetCache2XXResponseDnsCacheEntriesValue
		return ret
	}
	return *o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCache2XXResponseDnsCache) GetEntriesOk() (*map[string]GetCache2XXResponseDnsCacheEntriesValue, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *GetCache2XXResponseDnsCache) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given map[string]GetCache2XXResponseDnsCacheEntriesValue and assigns it to the Entries field.
func (o *GetCache2XXResponseDnsCache) SetEntries(v map[string]GetCache2XXResponseDnsCacheEntriesValue) {
	o.Entries = &v
}

func (o GetCache2XXResponseDnsCache) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCache2XXResponseDnsCache) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCache2XXResponseDnsCache) UnmarshalJSON(data []byte) (err error) {
	varGetCache2XXResponseDnsCache := _GetCache2XXResponseDnsCache{}

	err = json.Unmarshal(data, &varGetCache2XXResponseDnsCache)

	if err != nil {
		return err
	}

	*o = GetCache2XXResponseDnsCache(varGetCache2XXResponseDnsCache)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "stats")
		delete(additionalProperties, "entries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCache2XXResponseDnsCache struct {
	value *GetCache2XXResponseDnsCache
	isSet bool
}

func (v NullableGetCache2XXResponseDnsCache) Get() *GetCache2XXResponseDnsCache {
	return v.value
}

func (v *NullableGetCache2XXResponseDnsCache) Set(val *GetCache2XXResponseDnsCache) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCache2XXResponseDnsCache) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCache2XXResponseDnsCache) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCache2XXResponseDnsCache(val *GetCache2XXResponseDnsCache) *NullableGetCache2XXResponseDnsCache {
	return &NullableGetCache2XXResponseDnsCache{value: val, isSet: true}
}

func (v NullableGetCache2XXResponseDnsCache) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCache2XXResponseDnsCache) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


