/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: v3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seerr

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAuthJellyfinQuickconnectAuthenticateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAuthJellyfinQuickconnectAuthenticateRequest{}

// CreateAuthJellyfinQuickconnectAuthenticateRequest struct for CreateAuthJellyfinQuickconnectAuthenticateRequest
type CreateAuthJellyfinQuickconnectAuthenticateRequest struct {
	Secret string `json:"secret"`
	AdditionalProperties map[string]interface{}
}

type _CreateAuthJellyfinQuickconnectAuthenticateRequest CreateAuthJellyfinQuickconnectAuthenticateRequest

// NewCreateAuthJellyfinQuickconnectAuthenticateRequest instantiates a new CreateAuthJellyfinQuickconnectAuthenticateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAuthJellyfinQuickconnectAuthenticateRequest(secret string) *CreateAuthJellyfinQuickconnectAuthenticateRequest {
	this := CreateAuthJellyfinQuickconnectAuthenticateRequest{}
	this.Secret = secret
	return &this
}

// NewCreateAuthJellyfinQuickconnectAuthenticateRequestWithDefaults instantiates a new CreateAuthJellyfinQuickconnectAuthenticateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAuthJellyfinQuickconnectAuthenticateRequestWithDefaults() *CreateAuthJellyfinQuickconnectAuthenticateRequest {
	this := CreateAuthJellyfinQuickconnectAuthenticateRequest{}
	return &this
}

// GetSecret returns the Secret field value
func (o *CreateAuthJellyfinQuickconnectAuthenticateRequest) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *CreateAuthJellyfinQuickconnectAuthenticateRequest) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *CreateAuthJellyfinQuickconnectAuthenticateRequest) SetSecret(v string) {
	o.Secret = v
}

func (o CreateAuthJellyfinQuickconnectAuthenticateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAuthJellyfinQuickconnectAuthenticateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secret"] = o.Secret

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAuthJellyfinQuickconnectAuthenticateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAuthJellyfinQuickconnectAuthenticateRequest := _CreateAuthJellyfinQuickconnectAuthenticateRequest{}

	err = json.Unmarshal(data, &varCreateAuthJellyfinQuickconnectAuthenticateRequest)

	if err != nil {
		return err
	}

	*o = CreateAuthJellyfinQuickconnectAuthenticateRequest(varCreateAuthJellyfinQuickconnectAuthenticateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "secret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAuthJellyfinQuickconnectAuthenticateRequest struct {
	value *CreateAuthJellyfinQuickconnectAuthenticateRequest
	isSet bool
}

func (v NullableCreateAuthJellyfinQuickconnectAuthenticateRequest) Get() *CreateAuthJellyfinQuickconnectAuthenticateRequest {
	return v.value
}

func (v *NullableCreateAuthJellyfinQuickconnectAuthenticateRequest) Set(val *CreateAuthJellyfinQuickconnectAuthenticateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAuthJellyfinQuickconnectAuthenticateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAuthJellyfinQuickconnectAuthenticateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAuthJellyfinQuickconnectAuthenticateRequest(val *CreateAuthJellyfinQuickconnectAuthenticateRequest) *NullableCreateAuthJellyfinQuickconnectAuthenticateRequest {
	return &NullableCreateAuthJellyfinQuickconnectAuthenticateRequest{value: val, isSet: true}
}

func (v NullableCreateAuthJellyfinQuickconnectAuthenticateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAuthJellyfinQuickconnectAuthenticateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


